name: tkd_brackets
description: Tournament bracket management for Taekwondo competitions with offline-first capability.
version: 0.1.0+1
repository: https://github.com/YOUR_ORG/tkd_brackets
publish_to: none

environment:
  sdk: ^3.10.8

dependencies:
  bloc: ^9.0.0
  connectivity_plus: ^6.1.3
  csv: ^7.1.0
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  envied: ^1.3.2
  equatable: ^2.0.7
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_form_builder: ^10.2.0
  flutter_stripe: ^11.5.0
  form_builder_validators: ^11.1.0
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^8.0.1
  injectable: ^2.5.0
  internet_connection_checker_plus: ^2.6.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  printing: ^5.14.2
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  sentry_flutter: ^8.12.0
  share_plus: ^12.0.1
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.8.4
  syncfusion_flutter_charts: ^32.2.4
  syncfusion_flutter_pdf: ^32.2.4
  universal_html: ^2.3.0
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  web: ^1.1.0
  zentoast: ^0.2.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  drift_dev: ^2.23.1
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.9.0
  injectable_generator: ^2.6.3
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/l10n/
